# Generated by Django 4.0.3 on 2022-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'verbose_name': 'Yapılacak', 'verbose_name_plural': 'Yapılacaklar'},
        ),
        migrations.AddField(
            model_name='todomodel',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Bitti mi ?'),
        ),
    ]
